set MATLAB=D:\Program Files\MATLAB\R2015a
"D:\PROGRA~1\MATLAB\R2015a\bin\win64\gmake" -f sPort.mk  EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 ISPROTECTINGMODEL=NOTPROTECTING OPTS="-DON_TARGET_WAIT_FOR_START=0"
